- diagnostics:
  - psis_khat
  inference_engine: bayesbench_stan.meanfield_advi
  method_specific_arguments:
    iter: 1000
    tol_rel_obj: 0.01
  output_dir: out
  posterior_db_location: /home/eero/default_posterior_db
  posterior_name: 8_schools_noncentered
- diagnostics:
  - psis_khat
  inference_engine: bayesbench_stan.fullrank_advi
  method_specific_arguments:
    iter: 1000
    tol_rel_obj: 0.01
  output_dir: out
  posterior_db_location: /home/eero/default_posterior_db
  posterior_name: 8_schools_noncentered
